"""Patcher v0.1 — document-level XML parse/serialize (decision 0028 §7).

Serialization ALWAYS operates on the ElementTree (document level), never on
the root alone, so comments/PIs before/after the document element and XML
declaration semantics (version/encoding/standalone) survive the patch.

Parser settings mirror the frozen parser: resolve_entities=False,
no_network=True, recover=False, DTD/DOCTYPE rejected.
"""

from __future__ import annotations

import io

from lxml import etree

from .model import PatcherIntegrityError


def _xml_parser() -> etree.XMLParser:
    return etree.XMLParser(
        resolve_entities=False,
        no_network=True,
        remove_blank_text=False,
        strip_cdata=False,
        recover=False,
        huge_tree=False,
    )


def parse_document_xml(data: bytes, part_name: str) -> etree._ElementTree:
    """Parse one OOXML part at document level (ElementTree, docinfo kept)."""

    if b"<!DOCTYPE" in data.upper():
        raise PatcherIntegrityError(f"DTD/DOCTYPE is not allowed in OOXML part: {part_name}")
    try:
        return etree.parse(io.BytesIO(data), parser=_xml_parser())
    except (etree.XMLSyntaxError, ValueError) as exc:
        raise PatcherIntegrityError(f"malformed XML in {part_name}: {exc}") from exc


def _has_xml_declaration(original_bytes: bytes) -> bool:
    """Return whether the original part had an XML declaration.

    For UTF-8/ASCII-compatible documents this is a direct lexical check.
    For UTF-16/UTF-32 documents, lxml's docinfo is authoritative and the BOM
    plus decoded declaration semantics are handled by ElementTree serialization.
    """

    stripped = original_bytes.lstrip()
    if stripped.startswith(b"<?xml"):
        return True
    # Common UTF-16/32 BOMs: a BOM-backed XML document with declaration is
    # represented by libxml2 in docinfo; OOXML generated by Word normally has
    # one. We preserve declaration semantics whenever docinfo exposes them.
    return original_bytes.startswith((b"\xff\xfe", b"\xfe\xff", b"\x00\x00\xfe\xff", b"\xff\xfe\x00\x00"))


def serialize_document_xml(tree: etree._ElementTree, original_bytes: bytes) -> bytes:
    """Serialize the full document tree using the original XML encoding.

    Unlike replaying a raw declaration over UTF-8 bytes, this preserves the
    declaration *semantics*: the serialized payload encoding matches
    ``tree.docinfo.encoding`` and standalone is carried through when present.
    Document-level comments/PIs are retained because the ElementTree itself is
    serialized. No namespace cleanup is performed.
    """

    docinfo = tree.docinfo
    encoding = docinfo.encoding or "UTF-8"
    has_declaration = _has_xml_declaration(original_bytes)
    standalone = docinfo.standalone
    kwargs = {
        "encoding": encoding,
        "xml_declaration": has_declaration,
    }
    if standalone is not None:
        kwargs["standalone"] = standalone
    try:
        return etree.tostring(tree, **kwargs)
    except (LookupError, ValueError, TypeError) as exc:
        raise PatcherIntegrityError(
            f"unable to serialize word/document.xml in original encoding {encoding!r}: {exc}"
        ) from exc
